Filter refactor
likablehair/svelte pull request #39
Opened 2024-04-03 10:00 UTC by dsonlieti

- nuova vista filtri (unico dialog in cui è possibile comporre i filtri a piacimento)
- aggiunta la funzione modify su ogni tipo di filtro per poter creare query custom
- nuova gestione filtri custom (nello slot custom viene passata come prop la funzione 'updateFunction' che si occupa di aggiornare il valore interno del filtro, da chiamare ogni volta che cambia l'input passandogli il nuovo valore)
- possibilità di scegliere il componente per i filtri di tipo select ('toggle' | 'autocomplete', di default 'autocomplete')

2024-04-03 13:25 UTC, GabrieleGarlaschelli reviewed
Ho un errore typescript nella PaginedTable.svelte, nel metodo handleSearchChange, sul costruttore della classe. Me lo sistemi?

2024-04-03 14:03 UTC, GabrieleGarlaschelli requested changes

2024-04-03 14:03 UTC, GabrieleGarlaschelli commented on src/lib/components/composed/forms/DatePickerTextField.svelte
> +          <slot name="prepend" {prependIcon} {iconSize}>
Anche questa è una modifica tosta, bisogna ricordarci di controllare nei vari applicativi se il contenuto degli slot torna

2024-04-03 14:03 UTC, GabrieleGarlaschelli commented on src/lib/components/composed/search/FilterEditor.svelte
> +  import Icon from "$lib/components/simple/media/Icon.svelte";
indentami bene dai

2024-04-03 14:03 UTC, GabrieleGarlaschelli commented on src/lib/components/composed/search/FilterEditor.svelte
> +    import VerticalSwitch from "$lib/components/simple/forms/VerticalSwitch.svelte";
Dovrebbero essere due componenti non utilizzati

2024-04-03 14:41 UTC, dsonlieti commented on src/lib/components/composed/forms/DatePickerTextField.svelte
> +  $: if(!selectedDate) {
Ho fatto un po' di test e sembra che non rompa nulla

2024-04-04 08:51 UTC, GabrieleGarlaschelli approved these changes

2024-04-04 08:51 UTC, merged