Comp 22 file input
likablehair/svelte pull request #4
Opened 2022-06-24 12:49 UTC by davide-sonlieti

2022-06-24 13:44 UTC, GabrieleGarlaschelli requested changes
Ci sono un po' tante cose da guardare ma nel complessivo funziona.

2022-06-24 13:44 UTC, GabrieleGarlaschelli commented on src/lib/forms/FileInput.svelte
> +            nativeEvent: DragEvent
Qua magari passa anche il file che vengono aggiunti

2022-06-24 13:44 UTC, GabrieleGarlaschelli commented on src/lib/forms/FileInput.svelte
> +        }
Anche qua

2022-06-24 13:44 UTC, GabrieleGarlaschelli commented on src/lib/forms/FileInput.svelte
> +    class:elevated={dropAreaActive && !focusShadow && elevation}
Fai una sola variabile che contiene l'ombra, la imposti poi a default come è impostata nella classe `elevated`

2022-06-27 09:36 UTC, davide-sonlieti commented on src/lib/forms/FileInput.svelte
> +    <input
La proprietà HTMLInputElement.files è readonly

2022-06-28 13:14 UTC, GabrieleGarlaschelli commented on src/lib/forms/FileInput.svelte
> +    <input
Oke perfetto

2022-06-28 13:17 UTC, GabrieleGarlaschelli approved these changes
Ottimo

2022-06-28 13:19 UTC, merged