DUEDIL-610
likablehair/svelte pull request #54
Opened 2024-07-17 16:12 UTC by FabioRossi-99

Aggiunto slot per inserire del codice prima o dopo l'icona del componente UnstableDividedSidebarLayout

2024-07-17 16:29 UTC, GabrieleGarlaschelli requested changes

2024-07-17 16:29 UTC, GabrieleGarlaschelli commented on src/lib/components/simple/lists/ColorInvertedSelector.svelte
> +              <slot name="before-prepend" {option} {index}></slot>
Non ha senso mettere due slot vicini. Puoi usarne direttamente uno solo.

2024-07-17 16:29 UTC, GabrieleGarlaschelli commented on src/lib/components/simple/lists/ColorInvertedSelector.svelte
> +              {@html option.label}
questo mi puzza, perchè lo hai fatto?

2024-07-18 07:15 UTC, FabioRossi-99 commented on src/lib/components/simple/lists/ColorInvertedSelector.svelte
> +              <slot name="before-prepend" {option} {index}></slot>
L'ho messo perché ho bisogno che l'icona sia visibile e dovrei aggiungere del codice appena dopo l'icona

2024-07-18 07:17 UTC, FabioRossi-99 commented on src/lib/components/simple/lists/ColorInvertedSelector.svelte
> +              {@html option.label}
L'ho messo così perché se fosse necessario aggiungere del codice nella label almeno sarebbe visto correttamente (tanto non cambierebbe la visualizzazione di un semplice testo come parametro passato)

2024-07-18 08:18 UTC, FabioRossi-99 commented
Fatta la commit con le modifiche richieste

2024-07-29 07:39 UTC, GabrieleGarlaschelli commented on src/lib/components/simple/lists/ColorInvertedSelector.svelte
> +              <slot name="before-prepend" {option} {index}></slot>
Se devi aggiungere degli elementi appena dopo l'icona usa lo slot dell'icona, rimetti l'icona, e poi puoi mettere tutti gli elementi che vuoi prima e dopo

2024-07-29 07:39 UTC, GabrieleGarlaschelli commented on src/lib/components/simple/lists/ColorInvertedSelector.svelte
> +              {@html option.label}
Per quello si usa lo slot

2024-07-29 07:43 UTC, GabrieleGarlaschelli requested changes

2024-07-29 07:43 UTC, GabrieleGarlaschelli commented on src/lib/components/layouts/UnstableDividedSideBarLayout.svelte
> +                          {@html option.label}
No, qua devi togliere @html

2024-07-29 07:45 UTC, FabioRossi-99 commented on src/lib/components/layouts/UnstableDividedSideBarLayout.svelte
> +                          {@html option.label}
Fatto ✅

2024-07-29 13:38 UTC, merged